name: Build and Push ARM Docker Image

on:
  push:
    branches:
      - master
    tags:
      - '*'

env:
  IMAGE_NAME: eduardvalentin/eea-website-frontend

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Log in to DockerHub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Install Dependencies (if missing)
        run: |
          if [ ! -d "node_modules" ]; then
            echo "node_modules not found, running yarn install"
            yarn install --frozen-lockfile
          fi

      - name: Debug Yarn and Environment
        run: |
          yarn --version || echo "Yarn not installed"
          node --version || echo "Node not installed"
          echo "Current working directory: $(pwd)"
          echo "Contents of node_modules:"
          ls -al node_modules || echo "node_modules directory not found"

      - name: Determine Docker tag
        id: docker_tag
        run: |
          if [[ "${{ github.ref_name }}" == "master" ]]; then
            echo "tag=latest" >> $GITHUB_ENV
          else
            echo "tag=${{ github.ref_name }}" >> $GITHUB_ENV
          fi

      - name: Build and push Docker image (ARM)
        uses: docker/build-push-action@v5
        with:
          context: .
          platforms: linux/arm64
          push: true
          tags: |
            ${{ secrets.DOCKERHUB_USERNAME }}/${{ env.IMAGE_NAME }}:${{ env.tag }}
